name: telegram message
on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]
jobs:
  sender:
    name: sender
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull request send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'pull_request'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} відкрив Pull Request \"${{ github.event.pull_request.title }}\". ${{ github.event.pull_request.html_url }} 
      - name: issues send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'issues'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} відкрив Issue \"${{ github.event.issue.title }}\". ${{ github.event.issue.html_url }}
      - name: pull request review comment send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'pull_request_review_comment'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} прокоментував \"${{ github.event.comment.body }}\" в \"${{ github.event.pull_request.title }}\". ${{ github.event.comment.html_url }}
      - name: issue comment send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'issue_comment'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} прокоментував \"${{ github.event.comment.body }}\" в \"${{ github.event.issue.title }}\". ${{ github.event.comment.html_url }}
